#!/bin/sh
<<EOF

DROP TABLE MEMBERSHIP_LOG;
DROP TABLE REFEREEING_LOG;
DROP TABLE PLAYS_IN;
DROP TABLE GAMES;
DROP TABLE PLAYERS;
DROP TABLE CLUBS;
DROP TABLE STADIUMS;
DROP TABLE MANAGERS;
DROP TABLE REFEREES;
DROP TABLE PERSONS;
DROP TABLE CITIES;
DROP TABLE SEASONS;
exit;
EOF
